version: '3.9'
services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - sporthub:/var/lib/postgresql/data
      - ./src/init_data:/docker-entrypoint-initdb.d
  pgAdmin:
    image: dpage/pgadmin4:latest
    env_file: pgAdmin.env
    depends_on:
      - db
    ports:
      - '80:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_config:/pgadmin
  web:
    image: node:lts
    user: root
    working_dir: /home/node/app
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '1234:1234'
    volumes:
      - ./:/home/node/app
    command: 'npm run testandrun'
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
volumes:
  sporthub:
  pgadmin_data:
  pgadmin_config:
